// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



// confidential information removed
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    
    }
  

  static const FirebaseOptions web = FirebaseOptions(
    
  );

  static const FirebaseOptions android = FirebaseOptions(
    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    
  );

  static const FirebaseOptions macos = FirebaseOptions(
    
  );

  static const FirebaseOptions windows = FirebaseOptions(
    
  );
}
